version: "3"

services:
  web:
    build: "./client"
    volumes:
      - "./client:/usr/src/app"
    links:
      - server
    depends_on:
      - server
    ports:
      - "3000:3000"
    command: npm start

  server:
    build: "."
    volumes:
      - ".:/usr/src/app"
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - "9000:9000"
    command: npm run server

  db:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
